### ISSUE TITLE
Acquire & install chandelier

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#15]
....because the current light fixture is atrocious. Do we need a contractor for this?

Chandelier thoughts:
- http://www.homebase.co.uk/en/homebaseuk/vela-9-light-chrome-chandelier-446025
- https://www.gumtree.com/p/lighting-fittings/-gorgeous-large-elegant-6-light-french-style-chic-glass-crystal-chandelier/1185399379 (contacted via email; no response)
- https://www.gumtree.com/p/lighting-fittings/chandelier/1189704404 (I think this may be https://www.cotterellandco.com/katie-9-light-acrylic-glass-chandelier which actually looks pretty promising)

Might be worth visiting the lighting shop (https://www.cotterellandco.com) at some point to have a look at our options, get a sense of what we like, etc. 

Initial thoughts: relatively ornate, traditional, glass/crystal rather than acrylic, clear/silver tones.

**Comment by tofumatt** [comment]
Almost certainly this is something I'll just DIY when it comes time to install.

**Comment by tofumatt** [comment]
We did this! 🎉
