### ISSUE TITLE
Run electrics through office

### ISSUE THREAD

**Issue by tofumatt** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#16]
That thing is run off a single outlet, so make sure there's enough room to grow for two desks and the bookshelf itself.

Might be nice to put some phone/iPad/etc. chargers in the bookshelf itself too, could be handy and free up clutter from the desks!

**Comment by sarahmonster** [comment]
> Might be nice to put some phone/iPad/etc. chargers in the bookshelf itself too, could be handy and free up clutter from the desks!

❤️ 🔋

**Comment by tofumatt** [comment]
I did this and even put chargers in the bookshelf (only on my side, but that's enough as Sarah's desk has a big USB port stand thing).

Calling this finished.
