### ISSUE TITLE
Paint hallway

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#22]
I'm currently thinking white/pale grey with black skirting and brightly-painted doors, something like:

![french-grey-pale-161-jack-black-119-cape-red-2791](https://cloud.githubusercontent.com/assets/376315/18817802/df97cde8-8361-11e6-90de-6be8989c4b29.jpg)

(Little Greene French Grey Pale + Jack Black)

**Comment by tofumatt** [comment]
You did this! 🎉
