### ISSUE TITLE
Install gas fireplace

### ISSUE THREAD

**Issue by tofumatt** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#3]
Should be a relatively straightforward install as our flue is functional and we already installed the new gas line.

**Comment by sarahmonster** [comment]
http://webarchive.nationalarchives.gov.uk/20151113141044/http://www.planningportal.gov.uk/uploads/br/br_pdf_adj_2002.pdf for planning

**Comment by tofumatt** [comment]
Currently waiting on the contractor to come and check on everything and sweep the chimney.

Seems like we _may_ require a liner because of building age, and code might require a new hearth but hopefully not.
