### ISSUE TITLE
Source & purchase appliances

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#41]
### Current plan

- [x] Gorenje fridge/freezer, left opening
- [x] <del>Stoves Richmond 90cm range</del> Rangemaster Classic Deluxe 90cm
- [x] <del>Stoves Richmond 100cm A-rated hood (£500 instead of £200, with a rail)</del> Rangemaster hood?
- [x] Samsung ecobubble washer/dryer, of @tofumatt's choosing
- [x] Medelstor dishwasher, courtesy of IKEA

Fridge has been purchased, probably makes sense to wait a bit on the rest and order them once our cabinets are in place (or at least dry fitted!)

### Original plan
Prices should be entered into [budget sheet ](https://docs.google.com/spreadsheets/d/1DNba6SVPWWazZ_CHb3DrPTZMUq90jT7zsObfzXF1e-U/edit#gid=0) once known!

Cooker: [Rangemaster Classic Deluxe 90 dual-fuel](http://www.rangemaster.co.uk/products/range-cookers/classic-deluxe/classic-deluxe-90-dual-fuel) in black+brass

Hood: [Rangemaster](http://ao.com/product/clahdc110bb-rangemaster-classic-110-chimney-cooker-hood-black-25837-5.aspx); the [Gorenje](http://ao.com/product/dk63mclb-gorenje-classico-collection-chimney-cooker-hood-black-40108-5.aspx) is also cute but way too small.

Fridge:

Dishwasher: something around 45cm wide would be good; the [MEDELSTOR](http://www.ikea.com/gb/en/products/appliances/dishwashers/medelstor-integrated-dishwasher-grey-art-20299363/) from IKEA looks pretty nice but might actually be upper-range price-wise.

Washing machine:

Also sort out the installation details/costs & timing.

**Comment by sarahmonster** [comment]
Current contender for washer/dryer: WD80N645OOW

Amazing reviews, can get £150 cash back.

> Electrical supply and grounding
> • AC 220-240 V / 50 Hz fuse or circuit breaker is required
> • Use an individual branch circuit specific to the washing machine

> A proper water pressure for this washing machine is between 50 kPa and 800 kPa. Water pressure less than 50 kPa may cause the water valve not to close completely. Or, it may take longer to fill the drum, causing the washing machine to turn off. Water taps must be within 120 cm from the rear of the washing machine so that the provided inlet hoses reach the washing machine.

> For best performance, the washing machine must be installed on a solid floor. Wood floors may need to be reinforced to minimize vibration and/or unbalanced loads. 

From the manual here: http://downloadcenter.samsung.com/content/UM/201802/20180226112001760/WD90N645OOX_03924A-01_EN.pdf

Seems like we should ensure 25mm buffer at the top (before the worktop) and also potentially at the sides as well? (Not sure on this one.) We need 550 at the back, which is covered by the 7cm service void we're already making happen here, so all good there.

25mm at the top means 88cm is the lowest we should aim for the top of the cabinets to sit. To give us some extra wiggle room, let's hang the cabinets, at least on this side but perhaps throughout, at 90cm instead of 88.

For the flooring issue, we may want to try using an anti-vibration mat and/or a bit of plywood underneath to keep things a bit more level. See also: https://www.ukwhitegoods.co.uk/help/buying-advice/installation-advice/2729-installation-advice-installing-a-washing-machine-or-washer-dryer/

**Comment by tofumatt** [comment]
Places to buy from:

1. https://ao.com/product/wd80n645oow-samsung-quickdrive-washer-dryer-white-57242-2.aspx?cmredirectionvalue=WD80N645OOW £829 (free delivery?)
2. https://www.appliancesdirect.co.uk/p/wd80n645oow/samsung-wd80n645oow £808 (£19.95 delivery)

**Comment by sarahmonster** [comment]
YOU FINISHED THIS YAY.

Hood manual here: http://www.rangemaster.co.uk/media/1169349/li_9910279864.pdf

100 cm wide, needs to be installed at least 650mm above the cooker.

Cooker manual here: http://www.rangemaster.co.uk/media/4184697/u110719.pdf
