### ISSUE TITLE
Source & purchase sink-stuff

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#42]
Prices should be entered into [budget sheet ](https://docs.google.com/spreadsheets/d/1DNba6SVPWWazZ_CHb3DrPTZMUq90jT7zsObfzXF1e-U/edit#gid=0) once known!

Sink: [DOMSJÖ Onset sink, 2 bowls](http://www.ikea.com/gb/en/products/kitchen-products/kitchen-taps-sinks/domsj%C3%B6-onset-sink-2-bowls-white-spr-49158174/)

Taps: 
In terms of IKEA's offerings, I like [this one](http://www.ikea.com/gb/en/products/kitchen-products/kitchen-taps-sinks/glittran-kitchen-mixer-tap-black-art-50225610/) best.
But for basically the same price we could get [this](http://www.ebay.co.uk/itm/Kitchen-Sink-Tap-Mono-Mixer-Traditional-French-Classic-Tre-Mercati-Cross-Head-/321923238936) (gets [good reviews on Amazon](https://www.amazon.co.uk/Tre-Mercati-French-Classic-Antique/dp/B006MRVYDC/ref=pd_sbs_60_3?_encoding=UTF8&psc=1&refRID=YPDXQE1D7APG1M25PKPP) and is also available in a nice brass finish) or [this similar one](https://www.wayfair.co.uk/Belfry-Little-Venice-Mono-Single-Handle-Deck-Mounted-Sink-Mixer-BEFY9530-L653-K~BEFY9530.html?refid=GX77305791023-BEFY9530_19297697&device=c&ptid=144194859196&targetid=pla-144194859196&PiID%5B%5D=19297697&device=c&gclid=Cj0KEQiAifvEBRCVx5up6Ojgr5oBEiQALHw1Ttm4_HWINt7vWXpgm19dUFsRl14vNjEzq7zVxDnBF_saAs0c8P8HAQ)
or [this in brass](https://www.amazon.co.uk/ENKI-Traditional-Georgian-Antique-VICTORIA/dp/B01LXS378W/ref=sr_1_5?ie=UTF8&qid=1486842743&sr=8-5&keywords=copper+tap)

Are there other things we need to consider here? Accessories, dish-drying tray, probably a waste trap and some general plumbery stuff (what we need should be figured out in #37) and also a rubbish setup (I like the drawer-below-the-sink setup.)

**Comment by sarahmonster** [comment]
Currently thinking this: https://www.tapwarehouse.com/product/gosink2-mftantbrass-ehsantbrass?gclid=EAIaIQobChMIv6Hvhba_2AIVFLobCh0RFgmjEAkYHSABEgJXF_D_BwE&gclsrc=aw.ds

Tap, sink, and waste for £240 (can't tell if tap warehouse is like bath store in the "sale ends Monday!" department...), sink + waste is £150

**Comment by sarahmonster** [comment]
Some taps I think are groovy:

https://www.homary.com/uk/taps/kitchen-taps/splendid-high-arc-swiveling-dual-mode-pull-down-kitchen-mixer-tap-with-porcelain-lever.html?currency=GBP&gclid=EAIaIQobChMIkd2ptf6o3AIVVtwZCh2zuAIlEAkYFCABEgJWGPD_BwE

https://www.homary.com/uk/taps/kitchen-taps/modern-style-swan-neck-single-handle-spring-pull-out-kitchen-mixer-tap-brass-with-3-function-sprayer.html?currency=GBP&gclid=EAIaIQobChMIzr-_wv6o3AIVA_lRCh1ffAEPEAkYFyABEgK9cfD_BwE

https://www.homary.com/uk/taps/kitchen-taps/modern-single-handle-spring-pullout-kitchen-mixer-tap-with-dual-functions-in-multiple-finishes.html?currency=GBP&gclid=EAIaIQobChMI2ouX8P-o3AIVDNwZCh22SAdwEAkYESABEgIBG_D_BwE

https://www.homary.com/uk/antique-black-1-lever-pull-out-sprayer-monobloc-swanneck-kitchen-mixer-tap.html?currency=GBP&gclid=EAIaIQobChMIrP2czv-o3AIVGF8ZCh23KACzEAkYHSABEgJVxvD_BwE

https://www.homary.com/uk/taps/kitchen-taps/tracier-swanneck-monobloc-kitchen-mixer-tap-with-pull-out-spray.html?currency=GBP&gclid=EAIaIQobChMIzr-_wv6o3AIVA_lRCh1ffAEPEAkYDCABEgLZf_D_BwE

Also sidenote, but I super want one of these and am not sure it would work on a proper Belfast sink! 
https://www.ikea.com/gb/en/products/kitchen-products/kitchen-taps-sinks/domsj%C3%B6-colander-stainless-steel-art-20267338/ (It looks like the internet has lots of variants, including collapsible silicone ones, so we should be 💯 )

**Comment by tofumatt** [comment]
Only ones I like are:

Splendid High Arc Swiveling
Tracier Swanneck Monobloc
Antique Black 1-Lever Pull-Out Sprayer Monobloc Swanneck Kitchen Mixer Tap

I think we only agree on the first two 😄

**Comment by sarahmonster** [comment]
Note to ask plumber: https://www.tapwarehouse.com/product/reginox-panama-siphon

**Comment by sarahmonster** [comment]
DONE. Tap is already here and the sink is en route.
