### ISSUE TITLE
Source & purchase radiator

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#44]
Prices should be entered into [budget sheet ](https://docs.google.com/spreadsheets/d/1DNba6SVPWWazZ_CHb3DrPTZMUq90jT7zsObfzXF1e-U/edit#gid=0) once known!

I think a modern black vertical rad would be nice; [something along these lines](http://www.screwfix.com/p/ximax-erupto-square-vertical-designer-radiator-anthracite-1800-x-435mm/32658) or [this one](http://www.tradeplumbing.co.uk/eastgate-sheer-anthracite-vertical-flat-single-panel-designer-radiator-600mm-x-595mm.html) which you can then buy [a towel rail](http://www.tradeplumbing.co.uk/eastgate-chrome-towel-rail-for-eastgate-sheer-445mm.html) for.

We'll need to see about installing it as well—will need a gas safe engineer or a plumber or whatever for that.

**Comment by sarahmonster** [comment]
The space allotted for the radiator is around 970cm wide, so we may actually want to opt for a horizontal one, rather than a vertical one.

What about this: https://www.radiatoroutlet.co.uk/635-x-840mm-black-single-flat-panel-horizontal-radiator

**Comment by tofumatt** [comment]
Bought the double-stack version of that rad, and will handle the install. 👍
