### ISSUE TITLE
Source & purchase lighting

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#45]
Prices should be entered into [budget sheet ](https://docs.google.com/spreadsheets/d/1DNba6SVPWWazZ_CHb3DrPTZMUq90jT7zsObfzXF1e-U/edit#gid=0) once known!

Pendant lights for above bar (two or three, [something along these lines](http://www.ikea.com/gb/en/products/lighting/ceiling-lights/sl%C3%A4ttbo-pendant-lamp-copper-colour-art-00322901/) could be cute if we're short on space)

Plus a whole lot of worktop lighting (IKEA's [OMLOPP](http://www.ikea.com/gb/en/products/lighting/integrated-lighting/omlopp-led-worktop-lighting-aluminium-colour-art-10245219/) seems good). I could use some help figuring out what exactly we'll need once #36 is ready, but the kitchen designers might help with that as well.

Not sure what to do with the overhead lighting as of right now.

**Comment by sarahmonster** [comment]
Okay, so for lighting we want:

- one overhead light (wired in)
- one wall lamp over the sink (ideally wired)
- two or three pendants over the peninsula (again, wired would be nice but I care the least here)

## Pendants

<img width="492" alt="screenshot 2018-08-02 21 15 35" src="https://user-images.githubusercontent.com/376315/43608549-4095bb18-9699-11e8-9191-22217c6b3447.png">

https://www.pooky.com/pendant-lights/smaller-dexter-pendant-light-in-ash-black-with-white-interior-381#selection=pendant_colour_config:BRAASH__533;pendant_size_config:99__507, £95!


<img width="397" alt="screenshot 2018-08-02 21 16 39" src="https://user-images.githubusercontent.com/376315/43608602-6611b572-9699-11e8-82ab-c90717025d51.png">

https://www.dropbox.com/s/sn95spbgpvwhvrs/Screenshot%202018-08-02%2021.16.39.png?dl=0, £56

<img width="441" alt="screenshot 2018-08-02 21 20 09" src="https://user-images.githubusercontent.com/376315/43608760-e25ad99c-9699-11e8-9acf-728185174408.png">
https://www.pooky.com/sale/smaller-hector-pendant-in-gloss-black-with-a-stone-interior, £64

<img width="369" alt="screenshot 2018-08-02 21 21 07" src="https://user-images.githubusercontent.com/376315/43608799-0786e67a-969a-11e8-8c46-1ae17d9c8ee4.png">

https://www.pooky.com/pendant-lights/stanley-in-dark-grey-with-a-copper-interior-with-classic-pendant-light-kit-in-chrome-5986#selection=cc_option_2:100__945;cc_option_4:BRABRA__965;cc_option_3:CPK120__951;cc_option_1:IROGRC__1296, £66

<img width="404" alt="screenshot 2018-08-02 21 32 26" src="https://user-images.githubusercontent.com/376315/43609333-99decf28-969b-11e8-8d33-8555d741408b.png">

https://www.cultfurniture.com/lighting-c11/ceiling-lights-c61/factory-glass-cone-pendant-light-antique-gold-clear-p1695, £39


<img width="515" alt="screenshot 2018-08-02 21 33 40" src="https://user-images.githubusercontent.com/376315/43609400-c842df94-969b-11e8-99ad-ba1bb80f8b77.png">

https://www.cultfurniture.com/furniture-c10/industrial-black-metal-pendant-light-p1694, £39

<img width="416" alt="screenshot 2018-08-02 21 34 25" src="https://user-images.githubusercontent.com/376315/43609432-e5033d68-969b-11e8-805a-6c7494da471b.png">

https://www.cultfurniture.com/lighting-c11/ceiling-lights-c61/factory-glass-triple-pendant-light-colour-option-p7954, £79

## Overhead light

<img width="964" alt="screenshot 2018-08-02 20 55 12" src="https://user-images.githubusercontent.com/376315/43607622-9e8c8614-9696-11e8-8867-d7206a389629.png">

https://www.made.com/seppo-ceiling-bar-black, £69

<img width="484" alt="screenshot 2018-08-02 20 59 31" src="https://user-images.githubusercontent.com/376315/43607997-e806891a-9697-11e8-9cd7-8cb572d29b47.png">

https://www.made.com/ogilvy-rise-and-fall-pendant-matt-black-and-antique-brass, £79

## Wall light

We should go with Pooky for this one, since we've used them for every wall light throughout the flat. Depending on what we pick for the pendant, we may want to match/pair styles a bit as well.

<img width="478" alt="screenshot 2018-08-02 21 22 33" src="https://user-images.githubusercontent.com/376315/43608851-3379ac72-969a-11e8-86d9-25b247f993c1.png">

https://www.pooky.com/wall-lights/dexter-wall-light, £95

<img width="456" alt="screenshot 2018-08-02 21 26 03" src="https://user-images.githubusercontent.com/376315/43609000-b4e4067c-969a-11e8-9445-f69d54745f2d.png">


https://www.pooky.com/wall-lights/stanley-wall-light-in-petrol-blue-with-a-stone-interior-with-elbow-wall-fitting-in-antiqued-silver-2912#selection=cc_option_4:BRABRA__965;cc_option_3:ROS120__957;cc_option_2:100__945;cc_option_1:IROABS__936, £86

<img width="475" alt="screenshot 2018-08-02 21 27 55" src="https://user-images.githubusercontent.com/376315/43609091-f6164510-969a-11e8-8c44-5b5f20688865.png">

https://www.pooky.com/wall-lights/smaller-luxor-lantern-in-clear-glass-with-rose-wall-light-fitting-in-antiqued-brass, £86

**Comment by sarahmonster** [comment]
Alternate pendant option:

<img width="465" alt="screenshot 2018-08-07 11 31 52" src="https://user-images.githubusercontent.com/376315/43770939-a5663fb4-9a35-11e8-8180-ee2738956a7d.png">

https://www.pooky.com/sale/thea-pendant-light-in-bronze-with-brass-interior-374#selection=pendant_colour_config:BRABRC__529;pendant_size_config:100__521 (currently on sale for £86)

I like the black + copper combination here (so pretty!) but the fitting is a bit simpler, which obviously is a bit less to my liking, so it's a toss-up between this and the [Dexter in black/white](https://www.pooky.com/pendant-lights/smaller-dexter-pendant-light-in-ash-black-with-white-interior-381#selection=pendant_colour_config:BRAASH__533;pendant_size_config:99__507) right now.

**Comment by tofumatt** [comment]
I prefer the light not to stick out of the pendant, and I like the taller ones over the wider ones.

**Comment by sarahmonster** [comment]
Oh, it's also really big. I'd rather opt for smaller ones. Dexter is currently still my top contender, then!

**Comment by sarahmonster** [comment]
Ended up with Made's light bar and three [glass pendants](https://www.coxandcox.co.uk/glass-cone-pendant) from Cox + Cox. 

Still need to purchase cabinet lighting, and then we're in the clear here!

**Comment by tofumatt** [comment]
We'll also want drawer lighting, but I think we'll just want something like what we have in the bedroom wardrobe: battery-powered, motion-sensor LEDs stuck to the top of each drawer. These are what we have there: https://www.amazon.co.uk/gp/product/B01BGS112U/ref=oh_aui_search_detailpage?ie=UTF8&psc=1

I'll source something similar as it seems that seller is gone.

**Comment by tofumatt** [comment]
I'm taking this over as the only lights now needed are:

1. cabinet light for the upper cabinet (this will likely be a single or a few LED spotlights, hard-wired to the socket above the cabinet
2. drawer motion-sensor lights (
https://github.com/tofumatt/the-flat-that-matt-and-sarah-rebuilt/issues/45#issuecomment-413671293), probably with rechargeable batteries
3. possibly some under-shelf LEDs, we'll see
