### ISSUE TITLE
Source & purchase wall tiles & paint

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#46]
I'm thinking white metro tiles with black/dark grey grout.

Metro tiles  From £0.29 per tile from tonsoftiles.co.uk
Equivalent to £14.50 per m2

Anything that isn't tiled will need to be painted. I'm thinking a gentle colour—either a dusty pink to offset all the dark cabinetry or a super-pale duck-egg blue. (Little Greene has some [beautiful pinks](https://www.littlegreene.com/paint/colour/red-and-pink-paint/pink-paint).)

Pink ideas:
http://www.apartmenttherapy.com/everything-old-is-new-again-pink-kitchen-193480

**Comment by sarahmonster** [comment]
The bathroom is already pink, so we're going with a more muted grey (Little Greene's Inox) for the walls in the kitchen instead.

For the tiles, current plan is this:

<img width="684" alt="screenshot 2018-08-29 22 06 16" src="https://user-images.githubusercontent.com/376315/44815587-d1254880-abd7-11e8-945a-938a4e624ded.png">

Flat matt white 10x20 metro tiles (same as the bathroom, just flat rather than bevelled!) with a silver grout. 

Based on an estimate of 15sqm, we'll need 3 buckets of adhesive (I don't want to mix my own) and 2 bags of grout. We'll also want some tile edging strips (leaning toward white curved), a trowel or two, and a tile cutter.

wallsandfloors.co.uk has a 20% sale happening right now (code BANKHOL) so I'll likely order this lot this week, and hopefully storing them won't be super obnoxious.

We *could* get creative with placement:
https://www.apartmenttherapy.com/shake-it-up-5-creative-new-ways-to-lay-subway-tile-208519

... not a big fan of them stacked or vertical, but I do love the herringbone patterns. 

We could also use black or contrasting tile to create a border/edge:

https://www.apartmenttherapy.com/subway-tile-pattern-inspiration-installation-ideas-233369

...but I'd like to keep the edging pretty casual in the kitchen, since there's going to be a lot of tile, with lots of breaks at different points. Maybe just a nice-looking curved edging strip will do? (Going to a tile place may help with visuals here!)

**Comment by tofumatt** [comment]
Herringbone is kinda cool, but I’m pretty happy with regular subway tile. Up to you though, I guess. Is herringbone a lot more effort?

**Comment by sarahmonster** [comment]
More tile inspiration, including a sense of how flat v. bevelled and matt v. glossy works out:

https://www.wallsandfloors.co.uk/blog/white-metro-tiles-bathroom-10-customer-projects/#
https://www.wallsandfloors.co.uk/blog/white-metro-tiles-kitchen-customer-projects/

I'm definitely seeing more flat in kitchens...

**Comment by sarahmonster** [comment]
✅Paint was purchased a few days ago
✅15sqm of smooth matt metro tile (plus silver grout and adhesive) purchased just now

Tiles are scheduled to arrive after we get back from the GM, so we don't have to worry about storing them for a while. 

We'll need to pick up some edging/corner strips at some point and some tiling tools (a manual cutter, a trowel or two) but we're basically good to get tiling, once we have a kitchen again.
