### ISSUE TITLE
Source & purchase vanity components

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#47]
- [x] cabinet
- [x] basin
- [x] mirror
- [x] tap

We'll need a cabinet or table of some kind (I'd like to go vintage), a washbasin (I like the round ones), and a tap. (Probably a waste and stuff as well.)

I like this basin a lot: http://www.bathstore.com/products/cupid-gloss-black-marble-bowl-2180.html

If I can find a good vintage piece to repurpose, this would be really lovely:

http://www.apartmenttherapy.com/the-complete-guide-to-using-vintage-furniture-as-a-bathroom-vanity-215811

http://www.apartmenttherapy.com/renovation-inspiration-using-vintage-furniture-as-bathroom-sink-cabinets-consoles-210512

Should be around 70cm tall (27") and at least 60cm (23") wide/deep.

**Comment by tofumatt** [comment]
I think getting a mirror cut to exact size and style is our best option and doesn't seem prohibitively expensive. That way we can measure exactly what we want and will work.

Places like http://www.mirrorworld.co.uk/made-to-measure-mirrors-framed.asp seem good, around £150 new for a custom-made framed mirror.

**Comment by sarahmonster** [comment]
OH RIGHT I FINALLY DID THIS HELL YEAH.
