### ISSUE TITLE
Update lighting in hallway

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#59]
We'll maybe want to do this in a coordinated effort, particularly if we'll need an electrician.

I'd like a wall-mounted light across from the bathroom, since this is the darkest corner of the house at night.

Dig this one but I'm not sure if the brass conflicts with the silver walls:
https://www.cultfurniture.com/furniture-c10/factory-style-sconce-wall-light-brown-p1711

This is nice too:
https://www.cultfurniture.com/lighting-c11/wall-lamps-c86/industrial-metal-cone-wall-light-black-p7151

Super like this:
https://www.pooky.com/wall-lights/16cm-empire-shade-in-burmese-fans-block-printed-cotton-with-twiglet-wall-fitting-in-aluminium-and-brass#selection=cc_option_4:CALANG__1178;cc_option_3:TWI120__1176;cc_option_2:216__1043;cc_option_1:BCOCFA__913

but with this shade:
https://www.pooky.com/lampshades/15cm-20cm/16cm-empire-shade-in-persian-fans-block-printed-cotton-1573#selection=shade_size_config:16cm__895;shade_colour_config:BCOPFA__833

For the main hall, we might want to build something custom so we can turn the single light fitting into three connected lights, and get more dispersed light?

**Comment by sarahmonster** [comment]
I could see something like this being super pretty for the overhead lights: https://www.dowsingandreynolds.com/shop/diamond-cage-pendant-light-polished-copper/

Not sure if we can chain two or three together and string them down the hall without blowing a fuse (maybe with super low-wattage bulbs?) but we could talk to an electrician. If we want to do a string of three lights, we're going to need to build something custom from lighting components.

cc @tofumatt

**Comment by tofumatt** [comment]
FYI: You can totally strip together a few lightbulbs (even high wattage ones) on the same cable. It's totally fine, no worries 😄

**Comment by sarahmonster** [comment]
Planned & purchased!

1 Pooky twiglet light + shade in black/gold
10m [black & white stripey fabric cable](https://www.enamelshades.co.uk/collections/fabric-cable/products/black-white-round-fabric-braided-cable)
2 LED [filament-style bulbs](https://www.enamelshades.co.uk/collections/filament-light-bulbs/products/e27-4w-led-edison-spiral-filament-bulb)
2 [copper cage shades](https://www.dowsingandreynolds.com/shop/cage-light-shade-diamond-polished-copper/)
2 [copper two-entry ceiling roses](https://www.dowsingandreynolds.com/shop/multi-outlet-ceiling-rose-polished-copper/?attribute_number-of-entry-points=2+Cable+entry)
2 [copper lightbulb holders](https://www.dowsingandreynolds.com/shop/e27-light-bulb-holder-threaded-copper/)
1 [plug](https://www.dowsingandreynolds.com/shop/plug-black-3-amp/)

**Comment by tofumatt** [comment]
DONE 🎉
