### ISSUE TITLE
Order + install worktops!

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#61]
IKEA doesn't have a great solution, so we'll want to order from elsewhere. We'll also want to hire a carpenter (or something) to fit it, because our walls are going to make this a nightmare job and the kitchen will look roughly a million times better if the worktop is fitted nicely. (See: not finished with masking tape and caulk.)

I'll work on finding someone, but we won't actually need this until at least a month into the process, so it isn't a huge hurry just yet. 

I think we'll need around 5m total of countertop material, although I should have a better sense of dimensions once I get the final kitchen design. 🤞I suspect that'll put the worktop clocking in around £1-2k total for materials + install.

I'm liking this black walnut here a whole lot: https://www.worktop-express.co.uk/wood_worktops/black_american_walnut_worktops.html

Regular walnut is also 👌

Apparently we can hide the gap with an upstand, which may make fitting way easier: https://www.worktop-express.co.uk/wood_worktops/black_american_walnut_3M_80_18mm_worktop_upstand.html

Their worktops are 15% of until 7 August, but I don't think we'll have a solid decision sorted by then.  😭Ordering a few samples would be a good way to start though.

**Comment by sarahmonster** [comment]
Note: we'll be going with black walnut and having Worktop Express do all the fabrication, once we know for sure what precise dimensions we'll need. I have some rough numbers but we're waiting on the cabinets to be fully installed so we can be sure.

This is a super helpful guide: https://www.homebase.co.uk/ideas-advice/kitchen-and-bathroom/kitchen-fitting/how-to-replace-a-worktop

and also this: https://www.worktop-express.co.uk/gbu0-display/solid_wood_worktop_installation_instructions.html

**Comment by sarahmonster** [comment]
Worktops finally ordered today!

**Comment by tofumatt** [comment]
2/3 worktops installed, but the last bar one needs waiting until the cooker is here and the bar supports are built.

**Comment by sarahmonster** [comment]
THEY ALL FIT YAY.
