### ISSUE TITLE
Have floors fixed + paint floors

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#70]
Floors were sort of fixed, then I fixed the fixing. Used Bona Gap Master in the gaps between floorboards (in black). Primed with Zinsser BIN (~2.5L), tinted as dark a grey as possible (mid-grey) and then painted two coats of Little Greene floor paint in Lamp Black (~3L).

https://www.littlegreene.com/media/wysiwyg/Floor_Paint_2014.pdf

Next up is stenciling (can start Tuesday), followed by two or three coats of Bona Mega.

**Comment by sarahmonster** [comment]
DONE!

![56010681031__f1072aba-4f5f-426a-bd09-0c8e78e748a2](https://user-images.githubusercontent.com/376315/46358120-3698a900-c65e-11e8-9414-7303e4bfa37e.JPG)
![wadrkrkatkghzpidyuxkja](https://user-images.githubusercontent.com/376315/46358122-3698a900-c65e-11e8-8032-24df0aa38946.jpg)
![uiauz1zfsraoefnpc0xfkq](https://user-images.githubusercontent.com/376315/46358123-3698a900-c65e-11e8-88a1-c3716aa765ef.jpg)

Three coats of Bona Mega, so they should be super protected, but we can do a top-up coat after gthe cupboards are in if we want. According to the [technical data sheet](http://www.binghamlumber.com/wp-content/uploads/2015/06/Bona-Mega-Technical-Data-Sheet.pdf), the floor should be 70% cured after one day, 90% after three days, and 100% cured in a week. That means that we can start doing things (installing stuff, using ladders, etc) in there Friday morning, and by Tuesday morning it'll be pretty much bulletproof. 🍻

**Comment by tofumatt** [comment]
Goddamn that is so fucking cool.
